config/routes.rb
Rails.application.routes.draw do
  # Home page and sitemap routes
  root to: 'index#index'
  get 'index', to: 'index#index'
  get 'sitemap', to: 'index#sitemap'

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Search routes
  resources :search, only: [:index]

  # Employee routes
  resources :employees, param: :name do
    collection do
      get 'subject-specialists', to: 'employees#subject_specialists'
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]
  # get 'employees/absence', :to => redirect( "absences/new" ) #redirect old absence form route

  # Contact routes
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'

  # Map routes
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Computer routes
  get 'computers', to: 'computers#index', as: 'computers'
  get 'computers/index', to: 'computers#index'
  post 'computers/ping', to: 'computers#ping', as: 'computers_ping'
  get 'computers/availability', to: 'computers#availability', as: 'computers_availability'

  # Room booking routes
  resources :meeting_rooms, path: 'room-bookings', param: :room_name, only: [:index] do
    get 'available-rooms', to: 'available_rooms', on: :collection
    get 'book', to: 'meeting_rooms#new', as: 'new_booking_for', on: :member
    post 'create', as: 'create_booking_for', on: :member
  end
  get 'roomschedules', to: 'meeting_room_bookings#index' # old url redirect

  # New books routes
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # Inventory routes
  resources :barcode_files, path: 'inventory', only: [:new, :create, :index], path_names: { new: 'upload' }

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'

  # Jasmine specs page
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
  belongs_to :supervisor, class_name: 'Employee', foreign_key: 'supervisor_id'
  has_many :headed_departments, class_name: 'Department', foreign_key: 'department_head_id', dependent: :nullify
  has_many :subordinates, class_name: 'Employee', foreign_key: 'supervisor_id', dependent: :nullify
  has_many :offices, foreign_key: 'primary_employee_id', dependent: :nullify
  has_many :absences, foreign_key: 'employee_id', dependent: :nullify

  def first_last
    "#{first_name} #{last_name}"
  end

  def last_first
    "#{last_name}, #{first_name}"
  end

  def title_and_rank
    if rank.blank?
      title
    else
      "#{title} - #{rank}"
    end
  end

  def url_slug
    "#{first_name.downcase.tr('-', '_')}-#{last_name.downcase.tr('-', '_')}"
  end

  def self.find_by_url_slug(slug)
    return nil if slug.blank?
    name = slug.gsub('-', '||').tr('_', '-').split('||')
    return nil unless name.length == 2
    first = name[0]
    last = name[1]
    Employee.find_by(first_name: first, last_name: last)
  end

  def library_administrator?
    department.andand.department_name == 'administration'
  end

  def can_view_absences_of?(employee)
    if employee.id == id || employee.supervisor.id == id || library_administrator?
      return true
    else
      return false
    end
  end

  def can_approve_absences_of?(employee)
    if employee.supervisor.id == id || library_administrator?
      return true
    else
      return false
    end
  end

  def leave_time_used(absence_type, string = true)
    absence_type_id = AbsenceType.find_by(absence_type_name: absence_type).id
    last_july_1 = Chronic.parse('last july 1')
    minutes_used = Absence.where(
      "employee_id = ? and absence_type_id = ? \
      and end_date >= ? and approved=1", id, absence_type_id, last_july_1
    ).sum(:duration_minutes)

    if string
      return ChronicDuration.output(minutes_used * 60,
                                    limit_to_hours: true,
                                    format: :long) || '0 hours'
    else
      return minutes_used
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # List all employees
  def index
    @current_department = Department.find_by(department_name: params[:list])
    @current_department ||= Department.new
    @offices = Office.joins(:department).order('display_name asc')
    @employees = Employee.joins(:department).where('hide_from_public_views is null or hide_from_public_views = false')
                         .order('last_name asc, first_name asc')

    if params[:list].present?
      @offices = @offices.where(department_id: @current_department.id)
      @employees = @employees.where(department_id: @current_department.id)
    end

    @breadcrumb = ["<a href='#{employees_url}'>Employee Directory</a>"]
    @page_title = 'Employee Directory'
    if params[:list].present?
      @breadcrumb << @current_department.display_name
      @page_title = "#{@page_title}: #{@current_department.display_name}"
    end
    render
  end

  # List all subject specialists
  def subject_specialists
    @departments = Department.all.order(:display_name)
    @subjects = SubjectArea.includes(:subject_librarian).where.not(subject_librarian_id: nil).order('subject_name asc')

    @breadcrumb = ["<a href='#{employees_url}'>Employee Directory</a>", 'Subject Specialists']
    @page_title = 'Employee Directory: Subject Specialists'

    render
  end

  # Show the employee portal with links to various employee functions
  def portal
    authenticate_user!
    return access_denied unless current_user.andand.employee?

    @employee = current_user.employee
    @subordinates = @employee.subordinates.order(:last_name)
    if @employee.library_administrator?
      @subordinates = LibraryEmployee.all.order(:last_name)
    end

    @page_title = 'Employee Portal'
    render
  end

  # Edit a specific employee's info
  def edit
    @employee = Employee.find_by_url_slug(params[:name])
    return not_found unless @employee.present?

    authenticate_user!
    return access_denied unless current_user.employee == @employee

    @page_title = "Edit Information: #{@employee.first_last}"
  end

  def update
    @employee = Employee.find_by_url_slug(params[:name])
    return not_found unless @employee.present?

    authenticate_user!
    return access_denied unless current_user.employee == @employee

    if @employee.update(params.require(:employee).permit!)
      flash[:notice] = 'Your information was updated.'
      return redirect_to portal_employees_url
    else
      @page_title = "Edit Information: #{@employee.first_last}"
      render 'edit'
    end
  end

  # Show a page of common links for student workers
  def student_workers
    @page_title = 'Student Worker Links'
    render
  end
end

app/views/employees/_employee_groups.erb
<div class="employee-directory-menu dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="employee-directory-menu-button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Groups
  </button>
  <div class="dropdown-menu" role="menu" aria-labelledby="employee-directory-menu-button">
    <%= link_to("All", employees_url, class: "dropdown-item") %>
    <% Department.all.order(:display_name).each do |department|  %>
      <%= link_to(department.display_name, employees_url( :list => department.department_name ), class: "dropdown-item") %>
    <% end %>
    <div class="dropdown-divider"></div>
    <%= link_to("Subject Specialists", subject_specialists_employees_url, class: "dropdown-item") %>
  </div>
</div>

app/views/employees/edit.html.erb
<h1><%= @page_title %></h1>
<% if @employee.errors.any? %>
  <div class="form-errors alert alert-danger">
    <h2>Please correct the following errors:</h4>
    <ul>
      <% @employee.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= semantic_form_for(@employee, url: employee_url( name: @employee.id ), :html => {method: :put} ) do |f| %>
  <%= f.inputs do %>
    <%= f.input :email, :as => :email, :input_html => { :disabled => true } %>
    <%= f.input :first_name, :as => :string %>
    <%= f.input :last_name, :as => :string %>
    <%= f.input :phone, :as => :string %>
    <%= f.input :office, :as => :string %>
    <%= f.input :title, :as => :string %>
    <%= f.input :rank, :as => :string %>
    <%= f.input :department, collection: Department.all.order(:display_name).pluck(:display_name, :id) %>
    <%= f.input :supervisor, collection: Employee.all.order(:last_name, :first_name).pluck("CONCAT(last_name, ', ', first_name)", :id)  %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, :as => :button, :label => "Submit", :button_html => {:class => 'btn btn-default'} %>
  <% end %>
<% end %>

app/views/employees/index.html.erb
<h1><%= @page_title %></h1>
<%= render 'employee_groups' %>
<h2>People</h2>
<% if @employees.blank? %>
  <p>There are no employees to display.</p>
<% else %>
  <table class="employee-table table table-striped table-condensed">
    <thead>
      <th>Name</th>
      <th>Title</th>
      <th>Department</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Office</th>
    </thead>
    <% @employees.each do |employee| %>
      <tr>
        <td class="employee-name">
          <% if employee.libguides_profile_url.present?%>
            <%= link_to(employee.last_first, employee.libguides_profile_url) %>
          <% else %>
            <%= employee.last_first %>
          <% end %>
        </td>
        <td class="employee-title"><%= employee.title_and_rank %></td>
        <td class="employee-department"><%= employee.department.display_name %></td>
        <td class="employee-email"><%= link_to employee.email, employee_website_contacts_url( employee.url_slug ) %></td>
        <td class="employee-phone"><%= employee.phone %></td>
        <td class="employe-office"><%= employee.office %></td>
      </tr>
    <% end %>
  </table>
  <ul class='employee-mobile-list list-group'>
    <% @employees.each do |employee| %>
      <li class='list-group-item'>
        <h3><%= employee.last_first %></h3>
        <table class='table table-condensed'>
          <tr>
            <td>Title</td>
            <td><%= employee.title_and_rank %></td>
          </tr>
          <tr>
            <td>Department</td>
            <td><%= employee.department.display_name %></td>
          </tr>
          <tr>
            <td>Email</td>
            <td><%= link_to employee.email, employee_website_contacts_url( employee.url_slug ) %></td>
          </tr>
          <tr>
            <td>Phone</td>
            <td><%= employee.phone %></td>
          </tr>
          <tr>
            <td>Office</td>
            <td><%= employee.office %></td>
          </tr>
        </table>
      </li>
    <% end %>
  </ul>
<% end %>
<h2>Library Offices</h2>
<% if @offices.blank? %>
  <p>There are no offices to display.</p>
<% else %>
  <table class="employee-table table table-striped table-condensed">
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Location</th>
      <th>Department</th>
    </thead>
    <% @offices.each do |office| %>
      <tr>
        <td><%= if office.webpage_url.blank? then office.display_name else link_to office.display_name, office.webpage_url end %></td>
          <td class="office-name"><%= link_to office.email, employee_website_contacts_url( office.office_name ) %></td>
          <td><%= office.phone_number %></td>
          <td><%= office.location %></td>
          <td><%= office.department.display_name %></td>
        </tr>
      <% end %>
    </table>
    <ul class='employee-mobile-list list-group'>
      <% @offices.each do |office| %>
        <li class='list-group-item'>
          <h3><%= if office.webpage_url.blank? then office.display_name else link_to office.display_name, office.webpage_url end %></h3>
            <table class='table table-condensed'>
              <tr>
                <td>Email</td>
                <td><%= link_to office.email, employee_website_contacts_url( office.office_name ) %></td>
              </tr>
              <tr>
                <td>Phone</td>
                <td><%= office.phone_number %></td>
              </tr>
              <tr>
                <td>Location</td>
                <td><%= office.location %></td>
              </tr>
              <tr>
                <td>Department</td>
                <td><%= office.department.display_name %></td>
              </tr>
            </table>
          </li>
        <% end %>
      </ul>
    <% end %>

app/views/employees/portal.html.erb
<h1><%= @page_title %></h1>
<h2>Absences</h2>
<ul>
  <li><%= link_to "View Today's Absence Calendar", absences_by_date_url %></li>
  <li><%= link_to "Submit a New Absence Request", new_employee_absence_url( employee_name: @employee.url_slug ) %></li>
  <li><%= link_to "View My Absences", employee_absences_url( employee_name: @employee.url_slug ) %></li>
  <% @subordinates.each do |employee| %>
    <% next if employee == @employee %>
    <li><%= link_to "View and Approve #{employee.first_last}'s Absences", employee_absences_url( employee_name: employee.url_slug ) %></li>
  <% end %>
</ul>
<h2>Employee Functions</h2>
<ul>
  <li><%= link_to "File Manager", files_url %></li>
  <li><%= link_to "JCKL Wiki", "https://sites.google.com/a/ucmo.edu/jckl/home" %></li>
  <li><%= link_to "Purchase Request", new_new_book_request_url %></li>
  <li><%= link_to("Technology Guides and Tutorials", "https://sites.google.com/a/ucmo.edu/jckl-technology-guides-and-tutorials/") %>
    <li><%= link_to("Website Issue Tracker", "https://library.ucmo.edu/projects/projects/jckl-website/issues") %>
      <ul>
        <li><%= link_to("Submit an Issue", "https://library.ucmo.edu/projects/projects/jckl-website/issues/new") %>
        </ul>
      </li>
      <% if current_user.has_role?("administrator") %>
        <li><%= link_to "Site Administration", admin_dashboard_url %></li>
      <% end %>
    </ul>
    <h2>Your Information <%= link_to "Edit", edit_employee_url( name: @employee.url_slug ), :class => "tag tag-default" %></h2>
    <table class="table table-condensed table-striped">
      <tr>
        <td>Name</td>
        <td><%= @employee.first_last %></td>
      </tr>
      <tr>
        <td>Email</td>
        <td><%= @employee.email %></td>
      </tr>
      <tr>
        <td>Phone</td>
        <td><%= @employee.phone %></td>
      </tr>
      <tr>
        <td>Office</td>
        <td><%= @employee.office %></td>
      </tr>
      <tr>
        <td>Title</td>
        <td><%= @employee.title %></td>
      </tr>
      <tr>
        <td>Rank</td>
        <td><%= @employee.rank %></td>
      </tr>
      <tr>
        <td>Supervisor</td>
        <td><%= if @employee.supervisor.blank? then "N/A" else @employee.supervisor.first_last end %></td>
        </tr>
        <tr>
          <td>Department</td>
          <td><%= @employee.department.display_name %></td>
        </tr>
      </table>

app/views/employees/student_workers.html.erb
<h1><%= @page_title %></h1>
<p><%= Time.zone.now.strftime( "%A, %B %-d, %Y" ) %></p>
<ul>
  <li><%= link_to "JCKL", root_url %></li>
  <li><%= link_to "UCMO", "http://www.ucmo.edu" %></li>
  <li><%= link_to "Copy Card Sheet", "https://docs.google.com/spreadsheet/ccc?key=0AjbwSfvQNOs4dGRZNzdsYXBEeGRHUHVjZ3diTTV0VHc&usp=sharing" %></li>
  <li><%= link_to "Inventory", barcode_files_url %></li>
  <li><%= link_to "Reference Tracking System", "https://ucmo.libapps.com/libapps/login.php?site_id=5447" %></li>
  <li><%= link_to "Room Booking Schedule (JCKL website)", roomschedules_url %></li>
  <li><%= link_to "Room Booking Schedule (25Live)", "http://www.ucmo.edu/25/25" %></li>
  <li><%= link_to "Study Room Reservation Schedule", "https://ucmo.libapps.com/libapps/login.php?site_id=6742" %></li>
</ul>

app/views/employees/subject_specialists.html.erb
<h1><%= @page_title %></h1>
<%= render "employee_groups" %>
<table class="employee-table table table-striped table-condensed">
  <thead>
    <th>Subject</th>
    <th>Librarian</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Office</th>
  </thead>
  <% @subjects.each do |subject| %>
    <% next unless subject.subject_librarian.present? %>
    <tr>
      <td class="employee-subject" ><%= subject.subject_name %></td>
      <td class="employee-name">
        <% if subject.subject_librarian.libguides_profile_url.present? %>
          <%= link_to(subject.subject_librarian.last_first, subject.subject_librarian.libguides_profile_url) %>
        <% else %>
          <%= subject.subject_librarian.last_first %>
        <% end %>
      </td>
      <td class="employee-email">
        <%= link_to(subject.subject_librarian.email, employee_website_contacts_url( subject.subject_librarian.url_slug )) %>
      </td>
      <td class="employee-phone"><%= subject.subject_librarian.phone %></td>
      <td class="employe-office"><%= subject.subject_librarian.office %></td>
    </tr>
  <% end %>
</table>
<ul class="list-group employee-mobile-list">
  <% @subjects.each do |subject| %>
    <% next unless subject.subject_librarian.present? %>
    <li class="list-group-item">
      <h2><%= subject.subject_name %></h2>
      <table class="table table-condensed">
        <tr>
          <td>Librarian</td>
          <td><%= link_to(subject.subject_librarian.last_first, subject.subject_librarian.libguides_profile_url) %></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><%= link_to(subject.subject_librarian.email, employee_website_contacts_url( subject.subject_librarian.url_slug )) %></td>
        </tr>
        <tr>
          <td>Phone</td>
          <td><%= subject.subject_librarian.phone %></td>
        </tr>
        <tr>
          <td>Office</td>
          <td><%= subject.subject_librarian.office %></td>
        </tr>
      </table>
    </li>
  <% end %>
</ul>