config/routes.rb
Rails.application.routes.draw do
  # Home page and sitemap routes
  root to: 'index#index'
  get 'index', to: 'index#index'
  get 'sitemap', to: 'index#sitemap'

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Search routes
  resources :search, only: [:index]

  # Employee routes
  resources :employees, param: :name do
    collection do
      get 'subject-specialists', to: 'employees#subject_specialists'
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]
  # get 'employees/absence', :to => redirect( "absences/new" ) #redirect old absence form route

  # Contact routes
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'

  # Map routes
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Computer routes
  get 'computers', to: 'computers#index', as: 'computers'
  get 'computers/index', to: 'computers#index'
  post 'computers/ping', to: 'computers#ping', as: 'computers_ping'
  get 'computers/availability', to: 'computers#availability', as: 'computers_availability'

  # Room booking routes
  resources :meeting_rooms, path: 'room-bookings', param: :room_name, only: [:index] do
    get 'available-rooms', to: 'available_rooms', on: :collection
    get 'book', to: 'meeting_rooms#new', as: 'new_booking_for', on: :member
    post 'create', as: 'create_booking_for', on: :member
  end
  get 'roomschedules', to: 'meeting_room_bookings#index' # old url redirect

  # New books routes
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # Inventory routes
  resources :barcode_files, path: 'inventory', only: [:new, :create, :index], path_names: { new: 'upload' }

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'

  # Jasmine specs page
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/models/meeting_room.rb
class MeetingRoom < ApplicationRecord
  has_many :meeting_room_bookings, dependent: :nullify

  has_attached_file :photo,
                    styles: {
                      medium: '400x400'
                    }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :photo, less_than: 10.megabytes

  GOOGLE_CALENDAR_EMBED_BASE_URL = 'https://www.google.com/calendar/embed?showCurrentTime=0showSubscribeButton=0&showTz=0&showPrint=0&showTabs=0&showCalendars=0&wkst=1&bgcolor=%23e2e2e2&ctz=America%2FChicago'.freeze
  GOOGLE_CALENDAR_PAGE_BASE_URL = 'http://www.google.com/calendar/embed?mode=WEEK&ctz=America/Chicago'.freeze
  GOOGLE_CALENDAR_AVAILABILITY_BASE_URL = "https://www.googleapis.com/calendar/v3/freeBusy?key=#{Rails.application.secrets.google_api_key}".freeze

  def google_calendar_week_embed
    "#{GOOGLE_CALENDAR_EMBED_BASE_URL}&src=#{google_calendar_id}&mode=WEEK"
  end

  def google_calendar_week_page
    "#{GOOGLE_CALENDAR_PAGE_BASE_URL}&src=#{google_calendar_id}&mode=WEEK"
  end

  def medium_photo_url
    photo.andand.url(:medium)
  end

  def self.check_availability(start_time, end_time)
    params = {
      timeMin: start_time,
      timeMax: end_time,
      timeZone: 'US/Chicago',
      items: []
    }
    MeetingRoom.all.each do |room|
      params[:items] << {
        id: room.google_calendar_id
      }
    end

    response = RestClient.post(GOOGLE_CALENDAR_AVAILABILITY_BASE_URL, params.to_json, content_type: :json, accept: :json)
    data = JSON.parse(response.body)

    available_calendars = []
    data['calendars'].each do |calendar_id, data|
      available_calendars << calendar_id if data['busy'].blank?
    end

    available_rooms = MeetingRoom.where(google_calendar_id: available_calendars)
  end
end

app/controllers/meeting_rooms_controller.rb
class MeetingRoomsController < ApplicationController
  CONFIRMATION_MESSAGE = 'Your booking request was submitted. You should receive confirmation via email.'.freeze

  def index
    @rooms = MeetingRoom.all.order(:library_only, :floor, :room_name)
    @page_title = 'Room Booking Schedules'
    render
  end

  def available_rooms
    start_time = Chronic.parse(params[:start])
    end_time = Chronic.parse(params[:end])

    if start_time.present? && end_time.present? && start_time < end_time
      render json: MeetingRoom.check_availability(start_time, end_time)
    else
      render json: { errors: ['A start time and end time must be specified and in the correct order.'] }, status: 422
    end
  end

  def new
    @booking = MeetingRoomBooking.new
    @booking.meeting_room = MeetingRoom.find_by(room_name: params[:room_name])

    if @booking.meeting_room.andand.library_only && !current_user.andand.employee?
      if !user_signed_in?
        flash[:alert] = "Notice: Only library employees can book room #{@booking.meeting_room.display_name}. If you are a library employee, please <a href='#{new_user_session_url}'>log in</a>."
        return redirect_to meeting_rooms_url
      else
        flash[:alert] = "Notice: Only library employees can book room #{@booking.meeting_room.display_name}."
        return redirect_to meeting_rooms_url
      end
    end

    @page_title = "Book #{@booking.meeting_room.display_name}"
    @breadcrumb = ["<a href='#{meeting_rooms_url}'>Room Booking Schedules</a>", @page_title]
    render
  end

  def create
    @booking = MeetingRoomBooking.new(params.require(:meeting_room_booking).permit!)
    @booking.meeting_room = MeetingRoom.find_by(room_name: params[:room_name])
    @booking.requestor_name = current_user.andand.name || @booking.contact_name
    @booking.requestor_email = current_user.andand.email || @booking.contact_email

    if @booking.meeting_room.andand.library_only && !current_user.andand.employee?
      if !user_signed_in?
        flash[:alert] = "Notice: Only library employees can book room #{@booking.meeting_room.display_name}. If you are a library employee, please <a href='#{new_user_session_url}'>log in</a>."
        return redirect_to meeting_rooms_url
      else
        flash[:alert] = "Notice: Only library employees can book room #{@booking.meeting_room.display_name}."
        return redirect_to meeting_rooms_url
      end
    end

    if @booking.save
      flash[:notice] = CONFIRMATION_MESSAGE
      MeetingRoomsMailer.send_email(@booking).deliver_later
      redirect_to meeting_rooms_url
    else
      @page_title = "Book #{@booking.meeting_room.display_name}"
      @breadcrumb = ["<a href='#{meeting_rooms_url}'>Room Booking Schedules</a>", @page_title]
      render :new
    end
  end
end

app/views/meeting_rooms/index.html.erb
<h1><%= @page_title %></h1>
<%= react_component('MeetingRoomBrowser',
  initialRooms: @rooms.as_json(methods: [:medium_photo_url, :google_calendar_week_embed]),
  availabilityUrl: available_rooms_meeting_rooms_url,
  mapUrl: map_url,
  bookingUrl: new_booking_for_meeting_room_url(room_name: "|ROOMNAME|"))
%>

app/views/meeting_rooms/new.html.erb
<h1><%= @page_title %></h1>
<p>
  Note: If your event is within the next three (3) day, please use this form to book a room at JCKL, otherwise please use <a href="http://www.ucmo.edu/25/25">25Live</a>.
</p>
<p>
  University of Central Missouri faculty, staff, and students may reserve available rooms in the James C. Kirkpatrick Library.
</p>
<h2>Scheduling</h2>
<p>
  The facility is reserved on a first-come, first-served basis by application after the library scheduling has been completed. The reservation must be made in advance: two (2) full business days (no less than 48 hours) prior to the start of the event. UCM faculty, staff and students will have priority in the use of the facilities over general community events. Community patrons may be assessed a room rental fee. Please call Meeting & Conference Services at 660-543-4342 or stop by Union 301 for room rental rates.
</p>
<p>
  A written notification of cancellation must be submitted no later than one (1) full business day prior to the scheduled use of the facility. Failure to do so will result in revocation of facility use privileges of any individual and/or group that does not comply with the guidelines as stated herein.
</p>
<h2>Special Arrangements</h2>
<p>
  The Dean of Library Services determines which rooms are available for food and drinks. Only events that have been previously arranged with the Dean may have food and drinks. The requestor is responsible to see that this request is followed. Food services may be contacted at 660-543-4440. Food cannot be delivered prior to opening of facility. Library personnel does not arrange for set up. All set up is the responsibility of the user.
</p>
<p>
  The user will be responsible for setting up any special arrangement for furniture. Please call Meeting & Conference Services at 660-543-4342 or stop by Union 301 for room arrangements. A cleaning fee may be charged if the room/area is not returned to the original conditions.
</p>
<p>
  If special software is needed a room request must be accompanied with request for software noted in the additional information section no less than four (4) weeks in advance and your departmental budget may incur a charge for software purchase and installation by the Office of Technology, Library Services does not provide the specialty software. This does not guarantee room request will be approved.
</p>
<h2>Booking Form</h2>
<% if @booking.errors.any? %>
  <div class="form-errors alert alert-danger">
    <h2>Please correct the following errors:</h2>
    <ul>
      <% @booking.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= semantic_form_for(@booking, url: create_booking_for_meeting_room_url(room_name: @booking.meeting_room.andand.room_name)) do |f| %>
  <%= f.inputs do %>
    <%= f.input :contact_name, as: :string, label: "Name" %>
    <%= f.input :contact_email, as: :email, label: "Email Address" %>
    <%= f.input :contact_phone, as: :string, label: "Phone Number" %>
    <%= f.input :contact_address, as: :string, label: "Address" %>
    <%= f.input :contact_dept, as: :string, label: "Department/Organization" %>
    <%= f.input :meeting_room, as: :select, label: "Room", collection: MeetingRoom.all.order(:display_name).pluck(:display_name, :id) ,input_html: {disabled: true} %>
    <%= f.input :event_name, as: :string, label: "Event Title" %>
    <%= f.input :start_time, as: :string, label: "Booking Start Time", input_html: { class: "anytime-datetime" } %>
    <%= f.input :end_time, as: :string, label: "Booking End Time", input_html: { class: "anytime-datetime" } %>
    <%= f.input :setup_time, as: :select, label: "Setup Time", collection: ["0 minutes", "15 minutes", "30 minutes", "45 minutes", "60 minutes"] %>
    <%= f.input :takedown_time, as: :select, label: "Takedown Time", collection: ["0 minutes", "15 minutes", "30 minutes", "45 minutes", "60 minutes"] %>
    <%= f.input :attendance, as: :number, label: "Estimated Attendance" %>
    <%= f.input :recurrence, as: :text, label: "How often will this meeting recur? (if applicable)", input_html: { rows: "4" } %>
    <%= f.input :notes, as: :text, label: "Additional Information", input_html: { rows: "4" } %>
  <% end %>
  <p>By submitting this request, you have read and hereby agree to the guidelines as outlined above.</p>
  <%= f.actions do %>
    <%= f.action :submit, as: :button, label: "Submit", button_html: {class: 'btn btn-default'} %>
  <% end %>
<% end %>