config/routes.rb
Rails.application.routes.draw do
  # Home page and sitemap routes
  root to: 'index#index'
  get 'index', to: 'index#index'
  get 'sitemap', to: 'index#sitemap'

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Search routes
  resources :search, only: [:index]

  # Employee routes
  resources :employees, param: :name do
    collection do
      get 'subject-specialists', to: 'employees#subject_specialists'
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]
  # get 'employees/absence', :to => redirect( "absences/new" ) #redirect old absence form route

  # Contact routes
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'

  # Map routes
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Computer routes
  get 'computers', to: 'computers#index', as: 'computers'
  get 'computers/index', to: 'computers#index'
  post 'computers/ping', to: 'computers#ping', as: 'computers_ping'
  get 'computers/availability', to: 'computers#availability', as: 'computers_availability'

  # Room booking routes
  resources :meeting_rooms, path: 'room-bookings', param: :room_name, only: [:index] do
    get 'available-rooms', to: 'available_rooms', on: :collection
    get 'book', to: 'meeting_rooms#new', as: 'new_booking_for', on: :member
    post 'create', as: 'create_booking_for', on: :member
  end
  get 'roomschedules', to: 'meeting_room_bookings#index' # old url redirect

  # New books routes
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # Inventory routes
  resources :barcode_files, path: 'inventory', only: [:new, :create, :index], path_names: { new: 'upload' }

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'

  # Jasmine specs page
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/views/index/index.html.erb
<h1 class="sr-only">James C. Kirkpatrick Library Home Page</h1>
<section class="index-chat">
  <div>Are you having trouble? Librarians are here to help.</div>
  <div id="libchat_0d87ea30ebf2ab1d5c12a1bc01588deb"></div>
  <script type="text/javascript" src="//v2.libanswers.com/load_chat.php?hash=0d87ea30ebf2ab1d5c12a1bc01588deb"></script>
</section>
<section class="index-links">
  <div class="inner container">
    <div class="row">
      <div class="col-md-12">
        <div class="card-deck-wrapper">
          <div class="card-deck">
            <%= render 'shared/hours' %>
            <%= render 'shared/help' %>
            <%= render 'shared/computers' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<section class="index-news">
  <div class="inner container">
    <h2>Library News</h2>
    <div class="row">
      <div class="col-md-12">
        <% NewsItem.current_news.in_groups_of(4) do |group| %>
          <!--Start card deck-->
          <div class="card-deck-wrapper">
            <div class="card-deck">
              <% group.each do |news_item| %>
                <% if news_item.present? and news_item.andand.friendly_url.present? %>
                  <div class="news-item card" id="news-item-<%= news_item.id %>">
                    <% if news_item.news_image.present? %>
                      <div class="news-image">
                        <%= image_tag(news_item.news_image.url(:medium), alt: news_item.title, class: 'card-img-top')  %>
                      </div>
                    <% end %>
                    <div class="card-block">
                      <h3 class="card-title"><%= link_to news_item.title, news_item_url(friendly_url: news_item.friendly_url) %></h3>
                      <% if news_item.teaser.present? %>
                        <p class="card-text"><%= news_item.teaser %></p>
                      <% end %>
                      <%= link_to "Read More", news_item_url(friendly_url: news_item.friendly_url), class: "card-link" %>
                    </div>
                  </div>
                <% else %>
                  <div class="card blank-card"></div>
                <% end %>
              <% end %>
            </div>
          </div>
          <!--End card deck-->
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="social-media-icons col-md-4 offset-md-4">
        <a href="https://www.facebook.com/JCKLibrary" title="Facebook"><i class="fa fa-facebook-square fa-3x"></i></a>
        <a href="https://twitter.com/jcklibrary" title="Twitter"><i class="fa fa-twitter fa-3x"></i></a>
        <a href="http://instagram.com/jcklibrary" title="Instagram"><i class="fa fa-instagram fa-3x"></i></a>
        <a href="https://www.youtube.com/user/JCKLibraryUCM" title="YouTube"><i class="fa fa-youtube-play fa-3x"></i></a>
      </div>
    </div>
  </div>
</section>
<section class="index-new-books">
  <div class="inner container">
    <h2>New Arrivals</h2>
    <%= react_component('NewBooksSlider', {books: NewBook.randomized_new_books(30).as_json(methods: :quest_url) }) %>
    <%= link_to("View More New Arrivals", new_books_url, class: "btn btn-lg btn-primary new-books-view-more") %>
  </div>
</section>

app/views/index/sitemap.html.erb
<div class="page sitemap">
  <h1><%= page_title %></h1>
  <% NavigationMenuItem.roots.order( "position asc" ).each do |menu| %>
    <h2>
      <a <%= if menu.url then "href='#{menu.url}'".html_safe end %> <%= if menu.element_class then "class='#{menu.element_class}'".html_safe end %> <%= if menu.element_id then "id='#{menu.element_id}'".html_safe end %>>
        <%= menu.label.html_safe %>
      </a>
    </h2>
    <% if menu.children %>
      <% menu.children.order( "position asc" ).each do |child1| %>
        <h3>
          <a <%= if child1.url then "href='#{child1.url}'".html_safe end %> <%= if child1.element_class then "class='#{child1.element_class}'".html_safe end %> <%= if child1.element_id then "id='#{child1.element_id}'".html_safe end %>>
            <%= child1.label.html_safe %>
          </a>
        </h3>
        <% if child1.children %>
          <ul>
            <% child1.children.each do |child2| %>
              <li>
                <a <%= if child2.url then "href='#{child2.url}'".html_safe end %> <%= if child2.element_class then "class='#{child2.element_class}'".html_safe end %> <%= if child2.element_id then "id='#{child2.element_id}'".html_safe end %>>
                  <%= child2.label.html_safe %>
                </a>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/index/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
  <urlset xmlns="http://www.google.com/schemas/sitemap/0.90">
    <url>
      <loc>https://library.ucmo.edu/</loc>
      <lastmod><%= Time.now.strftime( "%Y-%m-%d" ) %></lastmod>
      <changefreq>daily</changefreq>
      <priority>1</priority>
    </url>
    <% NavigationMenuItem.all.order( "label asc" ).each do |item| %>
      <% if item.url %>
        <url>
          <loc><%= item.url %></loc>
        </url>
      <% end %>
    <% end %>
  </urlset>