config/routes.rb
Rails.application.routes.draw do
  # Home page and sitemap routes
  root to: 'index#index'
  get 'index', to: 'index#index'
  get 'sitemap', to: 'index#sitemap'

  # Hours routes
  resources :library_hours, only: [:index], path: 'hours'

  # News routes
  resources :news_items, path: 'news', only: [:index, :show], param: :friendly_url

  # Search routes
  resources :search, only: [:index]

  # Employee routes
  resources :employees, param: :name do
    collection do
      get 'subject-specialists', to: 'employees#subject_specialists'
      get 'portal'
      get 'student-workers', to: 'employees#student_workers'
    end

    resources :absences do
      patch 'approve', on: :member
      patch 'reject', on: :member
      patch 'receive_note', on: :member
    end
  end
  get 'absences', to: 'absences#by_date', as: 'absences_by_date'
  get 'absences/:date', to: 'absences#by_date'

  resources :absences, only: [:new, :create, :index]
  # get 'employees/absence', :to => redirect( "absences/new" ) #redirect old absence form route

  # Contact routes
  resources :website_contacts, path: 'contact', only: [:create] do
    collection do
      get 'general'
      get 'employee/:name', action: 'employee', as: 'employee'
      get 'office/:name', action: 'office', as: 'office'
      get 'info'
    end
  end
  get 'contact', to: 'website_contacts#general'

  # Map routes
  get 'map', to: 'map#index', as: 'map'
  get 'map/index', to: 'map#index'

  # Computer routes
  get 'computers', to: 'computers#index', as: 'computers'
  get 'computers/index', to: 'computers#index'
  post 'computers/ping', to: 'computers#ping', as: 'computers_ping'
  get 'computers/availability', to: 'computers#availability', as: 'computers_availability'

  # Room booking routes
  resources :meeting_rooms, path: 'room-bookings', param: :room_name, only: [:index] do
    get 'available-rooms', to: 'available_rooms', on: :collection
    get 'book', to: 'meeting_rooms#new', as: 'new_booking_for', on: :member
    post 'create', as: 'create_booking_for', on: :member
  end
  get 'roomschedules', to: 'meeting_room_bookings#index' # old url redirect

  # New books routes
  resources :new_books, path: 'new-books', only: [:index] do
    get 'mappings', on: :collection
  end
  get 'newbooks', to: 'new_books#index'

  # Purchase request routes
  resources :new_book_requests, path: 'purchase-request', only: [:new, :create]
  get 'purchase-request', to: 'new_book_requests#new'

  # DVD routes
  get 'dvds', to: 'dvds#index', as: 'dvds'
  get 'dvds/index', to: 'dvds#index'

  # Stats routes
  get 'stats', to: 'stats#dashboard'
  get 'stats/dashboard', to: 'stats#dashboard', as: 'stats_dashboard'
  get 'stats/headcount_form', to: 'stats#headcount_form', as: 'stats_headcount_form'
  post 'stats/headcount_form', to: 'stats#headcount_form'
  get 'stats/headcounts', to: 'stats#headcounts', as: 'stats_headcounts'
  get 'stats/studyrooms', to: 'stats#studyrooms', as: 'stats_studyrooms'
  get 'stats/computers', to: 'stats#computers', as: 'stats_computers'

  # Inventory routes
  resources :barcode_files, path: 'inventory', only: [:new, :create, :index], path_names: { new: 'upload' }

  # File upload routes
  resources :files

  # Horses in Culture routes
  get 'horses_in_culture/data', to: 'horses_in_culture#data', as: 'horses_in_culture_data'

  # Error handling
  match '/401', to: 'errors#unauthorized', via: :all, as: 'error_unauthorized'
  match '/404', to: 'errors#not_found', via: :all, as: 'error_not_found'
  match '/422', to: 'errors#unprocessable', via: :all, as: 'error_unprocessable'
  match '/500', to: 'errors#internal_server_error', via: :all, as: 'error_internal_server_error'

  # Devise and ActiveAdmin authentication
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:omniauth_callbacks] = 'omniauth_callbacks'
  devise_config[:controllers][:registrations] = 'devise/registrations'
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)
  get 'omniauth_callbacks/all'

  # Jasmine specs page
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
end

app/views/shared/_breadcrumb.erb
<div class="breadcrumb" id="jckl-breadcrumb">
  <%= link_to "JCKL Home", root_url %>
  <% breadcrumb.each do |chunk| %>
    / <%= chunk.html_safe %>
  <% end %>
</div>

app/views/shared/_browser_update.erb
<script type="text/javascript">
  var $buoop = {
    vs:{i:8,f:15,o:12,s:5,c:30},
    text: "Your browser (%s) is out of date. Pages may load slowly and appear broken. For the best experience, <a%s>please update your browser</a>.",
    reminder: 0
  };
  $buoop.ol = window.onload;
  window.onload=function(){
   try {if ($buoop.ol) $buoop.ol();}catch (e) {}
   var e = document.createElement("script");
   e.setAttribute("type", "text/javascript");
   e.setAttribute("src", "//browser-update.org/update.js");
   document.body.appendChild(e);
  }
</script>

app/views/shared/_chat_popout.erb
<div id="libchat_4e53710117fc4aa6e3c4566aef11f4ca"></div><script type="text/javascript" src="//v2.libanswers.com/load_chat.php?hash=4e53710117fc4aa6e3c4566aef11f4ca"></script>

app/views/shared/_computers.erb
<div class="computers-block card">
  <div class="card-block">
    <h2 class="card-title">Study Rooms and Computers</h2>
  </div>
  <ul class="computers-list">
    <li class="study-rooms"><i class="fa fa-users"></i><a href="<%= map_url( :menu => "studyroom" ) %>">Study Rooms</a>
      <a href="http://ucmo.libcal.com/booking/jckl-study-rooms" class="tag tag-default pull-right">
        Reserve Study Rooms
      </a>
    </li>
    <li class="computers"><i class="fa fa-laptop"></i><a href="<%= map_url( :menu => "lab" ) %>">Computers</a>
      <a href="<%= map_url( :menu => "lab" ) %>" class="tag tag-default pull-right">
        <%= Rails.cache.fetch( "available_computers_count/") or 0 %> available
      </a>
    </li>
    <li class="room-bookings"><i class="fa fa-calendar"></i><a href="<%= roomschedules_url %>">Other Rooms</a></li>
    <li class="printing"><i class="fa fa-print"></i><a href="http://guides.library.ucmo.edu/printinghelp">Printing Help</a></li>
    <li class="off-campus"><i class="fa fa-unlock-alt"></i><a href="http://guides.library.ucmo.edu/offcampus">Off-Campus Database Access</a></li>
  </ul>
</div>

app/views/shared/_crazy_egg.erb
<!-- Crazy Egg analytics script -->
<script type="text/javascript">
  setTimeout(function(){var a=document.createElement("script");
    var b=document.getElementsByTagName("script")[0];
    a.src=document.location.protocol+"//dnn506yrbagrg.cloudfront.net/pages/scripts/0025/1442.js?"+Math.floor(new Date().getTime()/3600000);
    a.async=true;a.type="text/javascript";b.parentNode.insertBefore(a,b)}, 1);
</script>

app/views/shared/_footer.erb
<footer class="footer" id="jckl-footer">
  <div class="inner container">
    <h2 class="sr-only">More Navigation Options</h2>
    <div class="footer-columns footer-navigation-menu row">
      <% cache( NavigationMenuItem.cache_key + "-footer" ) do %>
        <% NavigationMenuItem.roots.each do |menu| %>
          <div class="footer-column col-md-<%= (12 / NavigationMenuItem.roots.length ) %>">
            <h3><%= menu.label %></h3>
            <ul>
              <% menu.children.order(:position).each do |submenu| %>
                <% if submenu.url.present? and submenu.show_in_footer %>
                  <li><a class="nav-menu-item-<%= submenu.id %> dropdown-item" href="<%= submenu.url %>"><%= submenu.label %></a></li>
                <% end %>
                <% submenu.children.order(:position).each do |nav_link| %>
                  <% next unless nav_link.show_in_footer %>
                  <li><a class="nav-menu-item-<%= nav_link.id %> dropdown-item" href="<%= nav_link.url %>"><%= nav_link.label %></a></li>
                <% end %>
              <% end %>
            </ul>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="footer-bottom">
      <h2 class="sr-only">Site Information</h2>
      <p>
        <span>James C. Kirkpatrick Library</span> | <span>601 South Missouri </span> | <span>Warrensburg, MO 64093</span> | <span>660-543-4565</span> | <span><a href="<%= root_url %>">Library Home Page</a></span>
      </p>
      <p>
        <span>University of Central Missouri</span> | <span>P.O. Box 800</span> | <span>Warrensburg, MO 64093</span> | <span>877-729-8266</span> | <span><a href="http://www.ucmo.edu">University Home Page</a></span>
      </p>
      <p>
        <% if user_signed_in? %>
          <span>Signed in as <%= current_user.name %></span> |
        <% if current_user.employee? %>
            <span><%= link_to "Employee Portal", portal_employees_url %></span> |
        <% end %>
          <span><%= link_to "Sign out", destroy_user_session_path, :data => {confirm: "Are you sure?"}, :method => :delete %></span>
        <% else %>
          <span><%= link_to "Employee Login", user_google_oauth2_omniauth_authorize_path %></span>
        <% end %>
      </p>
    </div>
  </div>
</footer>

app/views/shared/_google_analytics.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    //for library.ucmo.edu
    var ga_site_id = 'UA-19173945-1';

    //for libguides
    //var ga_site_id = 'UA-19173945-3';

    //for centralspace
    //var ga_site_id = 'UA-19173945-4';

    //for ezproxy
    //var ga_site_id = 'UA-19173945-7';

    //for illiad
    //var ga_site_id = 'UA-19173945-6';

    //for serials solutions
    //var ga_site_id = 'UA-19173945-5';

    //for quest
    //var ga_site_id = 'UA-19173945-2';


    ga('create', ga_site_id, 'auto');

    //remove this block except for on library.ucmo.edu
    var ip = '<%= request.env['REMOTE_ADDR'].gsub( /\.[0-9]{1,3}$/, ".*") %>';
    ga('set', 'dimension1', ip);
    ga('set', 'dimension2', ip);
    ga('set', 'dimension3', ip);
    ga('set', 'dimension5', "<%= cookies[:ip_group] %>");
    ga('set', 'dimension6', "<%= cookies[:testing_group] %>");
    //end block

    ga('set', 'dimension4', window.location.host);
    ga('send', 'pageview');
</script>

app/views/shared/_header.erb
<a href="#content" class="sr-only sr-only-focusable">Skip to main content</a>
<a href="#jckl-search" class="sr-only sr-only-focusable">Skip to search</a>
<header class="header" id="jckl-header">
  <div class="inner <%= if @layout_template == "full_screen" then "container-fluid" else "container" end %>">
    <div class="row">
      <h2 class="sr-only">Main Navigation Menu</h2>
      <div class="col-md-4">
        <div class="jckl-logo">
          <a href="<%= root_url %>">
            <%= image_tag "logo.png", {alt: "James C. Kirkpatrick Library"} %>
          </a>
        </div>
      </div>
      <div class="nav-menus col-md-8">
        <h2 class="sr-only">University of Central Missouri Links</h2>
        <nav class="ucm-links dropdown">
          <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
            University of Central Missouri
          </a>
          <ul class="dropdown-menu" role="menu">
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://www.ucmo.edu/">UCM Home</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://ucmo.blackboard.com/">Blackboard</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://www.ucmbookstore.com/home.aspx">Bookstore</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://www.ucmo.edu/search/">Campus Directory</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://www.ucmo.edu/campusmap/">Campus Map</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://mail.ucmo.edu/">Google Apps @ UCM</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://mycentral.ucmo.edu/">MyCentral</a></li>
            <li role="presentation"><a role="menuitem" tabindex="-1" href="http://www.ucmo.edu/calendar/">University Calendar</a></li>
          </ul>
        </nav>
        <nav class="header-navigation-menu nav nav-inline" role="navigation">
          <% cache( NavigationMenuItem.cache_key ) do %>
            <% NavigationMenuItem.roots.each do |menu, i| %>
              <div class="nav-item dropdown">
                <a class="nav-menu-item-<%= menu.id %> nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><%= menu.label %></a>
                <div class="dropdown-menu">
                  <% menu.children.order(:position).each do |menu_section| %>
                    <section class="menu-section">
                      <header class="nav-menu-item-<%= menu_section.id %>"><%= menu_section.label %></header>
                      <% menu_section.children.order(:position).each do |nav_link| %>
                        <a class="nav-menu-item-<%= nav_link.id %> dropdown-item" href="<%= nav_link.url %>"><%= nav_link.label %></a>
                      <% end %>
                    </section>
                  <% end %>
                </div>
              </div>
            <% end %>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/shared/_help.erb
<div class="help-block card">
  <div class="card-block">
    <h2 class="card-title">
      <% if controller_name == "index" and action_name == "index" %>
        More Ways to Get Help
      <% elsif controller_name == "contact" and action_name == "info" %>
        <!-- No title -->
      <% else %>
        How to Get Help
      <% end %>
    </h2>
  </div>
  <ul>
    <li class="call"><i class="fa fa-phone"></i>Call us at 660-543-4283</li>
    <li class="sms"><i class="fa fa-mobile"></i>Text us at 660-230-0011</li>
    <li class="email"><i class="fa fa-envelope-o"></i><%= link_to("Send us an email", general_website_contacts_url) %></li>
    <li class="guides"><i class="fa fa-book"></i><%= link_to("Research Guides and Tutorials", "http://guides.library.ucmo.edu") %></li>
  </ul>
</div>

app/views/shared/_hours.erb
<div class="library-hours-block card">
  <div class="card-block">
    <h2 class="card-title">Today's Hours</h2>
  </div>
  <ul>
    <li>
      <%= link_to "JCK Library", library_hours_url, class: "library-hours-label" %>
      <% if LibraryHour.hours_today.andand.hours_display_text %>
        <%= link_to LibraryHour.hours_today.andand.hours_display_text, library_hours_url, class: "library-hours-display pull-right tag tag-default" %>
      <% end %>
    </li>
    <li>
      <i class="fa fa-calendar"></i><%= link_to "View Full Calendar", library_hours_url %>
    </li>
    <li>
      <i class="fa fa-ticket"></i><%= link_to "Upcoming Events At JCKL" %>
    </li>
  </ul>
</div>

app/views/shared/_search.erb
<section class="search" id="jckl-search">
  <!--[if (IE 9) | (!IE) ]><!-->
    <!--<![endif]-->
    <div class="inner container">
      <h2 class="sr-only">Search the Library</h2>
      <!--[if lt IE 9]>
        <form class="legacy-search" action="http://ucmo.summon.serialssolutions.com/search?" method="GET" target="_blank">
          <label>Central Search</label>
          <input class="search-text" type="text" name="s.q" />
          <input class="search-submit" type="submit" value="Search" />
        </form>
        <ul class="search-options">
          <li><a href="http://quest.searchmobius.org/search~S2">Library Catalog</a></li>
          <li><a href="https://cse.google.com/cse/publicurl?cx=008482031334759306552:qu4cl8vnzlk">JCKL Website Search</a></li>
          <li><a href="http://guides.library.ucmo.edu/az.php">Browse Databases</a></li>
          <li><a href="http://wd8cd4tk5m.search.serialssolutions.com/">Journal Directory</a></li>
          <li><a href="https://illiad.ucmo.edu/">ILLiad Interlibrary Loan</a></li>
          <li><a href="http://ucmo.summon.serialssolutions.com/advanced">Advanced Search</a></li>
        </ul>
      <![endif]-->
      <!--[if (IE 9) | (!IE) ]><!-->
      <%= react_component('Search', {prerender: true}) %>

      <% if include_search_options %>
      <div class="search-options clearfix">

        <button class="search-options-toggle btn btn-primary" type="button" data-toggle="collapse" data-target=".search-options-list" aria-expanded="false" aria-controls="search-options-list">
          More Ways to Search
        </button>
        <div class="search-options-list collapse list-group">
          <a class="list-group-item" href="http://quest.searchmobius.org/search~S2">Library Catalog</a>
          <a class="list-group-item" href="https://cse.google.com/cse/publicurl?cx=008482031334759306552:qu4cl8vnzlk">JCKL Website Search</a>
          <a class="list-group-item" href="http://guides.library.ucmo.edu/az.php">Browse Databases</a>
          <a class="list-group-item" href="http://wd8cd4tk5m.search.serialssolutions.com/">Journal Directory</a>
          <a class="list-group-item" href="https://illiad.ucmo.edu/">ILLiad Interlibrary Loan</a>
          <a class="list-group-item" href="http://ucmo.summon.serialssolutions.com/advanced">Advanced Search</a>
        </div>
      </div>
      <% end %>

    <!--<![endif]-->
      </div>
    </section>

app/views/shared/_sidebar.erb
<aside class="sidebar col-md-4" id="jckl-sidebar">
  <div class="inner">
    
    <%= render 'shared/hours' %>
    <%= render 'shared/help' %>
    <%= render 'shared/computers' %>
    
  </div>
</aside>

app/views/shared/_special_messages.erb
<% if SpecialMessage.unexpired.present? %>
  <section class="special-messages alert alert-warning">
    <div class="inner container">
      <% SpecialMessage.unexpired.each do |message| %>
        <div class="special-message">
          <div><b><%= message.title %></b></div>
          <div><%=  message.content.html_safe %></div>
        </div>
      <% end %>
    </div>
  </section>
<% end %>
<% if notice %>
  <section class="special-message alert alert-success">
    <div class="inner container">
      <%= notice.html_safe %>
    </div>
  </section>
<% end %>
<% if alert %>
  <section class="special-message alert alert-danger">
    <div class="inner container">
      <%= alert.html_safe %>
    </div>
  </section>
<% end %>